emit event eifupdated
marlinprotocol/Contracts pull request #83
Opened 2024-01-18 07:48 UTC by arnav-deep

2024-01-19 06:23 UTC, roshanr95 requested changes

2024-01-19 06:23 UTC, roshanr95 commented on contracts/enclaves/MarketV1.sol
> +    function _eifUpdate(bytes32 _job, string memory _metadata) internal {
rename to `_jobMetadataUpdate`

2024-01-19 06:23 UTC, roshanr95 commented on contracts/enclaves/MarketV1.sol
> +    function eifUpdate(bytes32 _job, string calldata _metadata) external onlyJobOwner(_job) {
rename to `jobMetadataUpdate`

2024-01-19 06:23 UTC, roshanr95 commented on contracts/enclaves/MarketV1.sol
> +    event EifUpdated(bytes32 indexed job, string metadata);
rename to `JobMetadataUpdated`

2024-01-21 18:10 UTC, arnav-deep commented on contracts/enclaves/MarketV1.sol
> +    function eifUpdate(bytes32 _job, string calldata _metadata) external onlyJobOwner(_job) {
Done

2024-01-21 18:10 UTC, arnav-deep commented on contracts/enclaves/MarketV1.sol
> +    function _eifUpdate(bytes32 _job, string memory _metadata) internal {
Done

2024-01-21 18:11 UTC, arnav-deep commented on contracts/enclaves/MarketV1.sol
> +    event EifUpdated(bytes32 indexed job, string metadata);
Done

2024-01-22 09:46 UTC, roshanr95 requested changes

2024-01-22 09:46 UTC, roshanrags commented on contracts/enclaves/MarketV1.sol
> +    function _jobMetadataUpdate(bytes32 _job, string memory _metadata) internal {
put this along with the other _job*

2024-01-22 09:46 UTC, roshanrags commented on contracts/enclaves/MarketV1.sol
> +    function jobMetadataUpdate(bytes32 _job, string calldata _metadata) external onlyJobOwner(_job) {
put this along with the other job*

2024-01-22 11:02 UTC, roshanr95 approved these changes

2024-01-22 11:03 UTC, merged